In [1]:
import numpy as np

In [2]:
# 1D array
arr = np.array([1, 2, 3, 4])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
# 2D array
arr2 = np.array([[1,2 ,3], [4, 5, 6]])

In [5]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((4, 6), 9)

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.arange(1, 10,2)

array([1, 3, 5, 7, 9])

In [11]:
np.linspace(1, 100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [12]:
arr = np.array([[1 ,2 ,3],[4, 5, 6],[7,8,9],[10, 4, 7]])

In [13]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  4,  7]])

In [14]:
arr.shape

(4, 3)

In [15]:
arr.size

12

In [16]:
arr.ndim

2

In [17]:
arr.dtype

dtype('int64')

In [18]:
arr1 = np.array([1 ,2 ,3], dtype = np.float32)
print(arr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10  4  7]]


In [19]:
arr1.dtype

dtype('float32')

In [20]:
n = arr1.astype(np.int64)
print(n)

[1 2 3]


In [21]:
n.dtype

dtype('int64')

In [22]:
arr.shape

(4, 3)

In [24]:
reshaped = arr.reshape(3,4)

In [25]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  4,  7]])

In [27]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  7])