In [5]:
import numpy as np

   ## Create a 3X3 array filled with random numbers and prints its shape.

In [6]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr.shape

(3, 3)

### Convert an array of floats [1.1, 2.2, 3.3] into integers.

In [10]:
float_arr = np.array([1.1, 2.2, 3.3])

In [11]:
float_arr

array([1.1, 2.2, 3.3])

In [16]:
int_arr = float_arr.astype(int)

In [17]:
int_arr

array([1, 2, 3])

### Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

In [19]:
arr = np.array([1,2,3,4,5,6])

In [20]:
arr

array([1, 2, 3, 4, 5, 6])

In [21]:
arr[[1,3,5]]

array([2, 4, 6])

### Reshape a 1D array of size 9 into a 3X3 matrix

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Use boolean masking to filter numbers greater than 50 in an array

In [27]:
arr = np.array([1, 23, 43, 65, 79, 43, 33, 22, 76, 210, 99, 101])

In [28]:
arr

array([  1,  23,  43,  65,  79,  43,  33,  22,  76, 210,  99, 101])

In [30]:
arr[arr>50]

array([ 65,  79,  76, 210,  99, 101])