In [1]:
import numpy as np
arr = np.array([[1, 2, 3,],[4, 5, 6], [7,8,9],[11, 12, 13]])

In [2]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [3]:
flat = arr.flatten()

In [4]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [5]:
flat[0]

np.int64(1)

In [6]:
flat[4]

np.int64(5)

In [7]:
flat[3:6]

array([4, 5, 6])

In [8]:
flat[:5]

array([1, 2, 3, 4, 5])

In [9]:
flat[3:]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [10]:
flat[-1]

np.int64(13)

In [11]:
flat[::-1]

array([13, 12, 11,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [12]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [13]:
b = flat[3:7].copy()

In [14]:
b

array([4, 5, 6, 7])

In [15]:
b[0] = 2222222

In [16]:
b

array([2222222,       5,       6,       7])

In [17]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [18]:
arr = np.array([1 ,34, 4, 23, 4, 9, 7, 66,7])

In [19]:
arr[[1, 4, 6]]

array([34,  4,  7])

In [20]:
arr[arr>4]

array([34, 23,  9,  7, 66,  7])